"""src.config — Centralized system configuration and constants."""
from __future__ import annotations

from src.config.constants import (
    ANPR_CAPTURE_INTERVAL,
    ANPR_SERVER_TIMEOUT,
    CAMERA_TIMEOUT,
    CLOUD_POST_TIMEOUT,
    DEFAULT_DB_PATH,
    DEFAULT_HOTSPOT_PASS,
    DEFAULT_HOTSPOT_SSID,
    DEFAULT_SERIAL_BAUDRATE,
    DEFAULT_SERIAL_PORT,
    DEFAULT_WEIGHT_THRESHOLD,
    DEFAULT_WIFI_WATCHDOG_INTERVAL,
    GLUVOK_BASE_URL,
    HOTSPOT_CON_NAME,
    INDIAN_PLATE_REGEX,
    INTER_CHAR_TIMEOUT_S,
    MAX_BUFFER_LEN,
    MAX_PARALLEL_CAMERA_WORKERS,
    POST_STABILITY_DURATION,
    SCALE_TIMEOUT,
    STABILITY_DURATION,
    STABILITY_TOLERANCE,
)
from src.config.manager import ConfigManager

config = ConfigManager()

__all__ = [
    "ANPR_CAPTURE_INTERVAL",
    "ANPR_SERVER_TIMEOUT",
    "CAMERA_TIMEOUT",
    "CLOUD_POST_TIMEOUT",
    "DEFAULT_DB_PATH",
    "DEFAULT_HOTSPOT_PASS",
    "DEFAULT_HOTSPOT_SSID",
    "DEFAULT_SERIAL_BAUDRATE",
    "DEFAULT_SERIAL_PORT",
    "DEFAULT_WEIGHT_THRESHOLD",
    "DEFAULT_WIFI_WATCHDOG_INTERVAL",
    "GLUVOK_BASE_URL",
    "HOTSPOT_CON_NAME",
    "INDIAN_PLATE_REGEX",
    "INTER_CHAR_TIMEOUT_S",
    "MAX_BUFFER_LEN",
    "MAX_PARALLEL_CAMERA_WORKERS",
    "POST_STABILITY_DURATION",
    "SCALE_TIMEOUT",
    "STABILITY_DURATION",
    "STABILITY_TOLERANCE",
    "ConfigManager",
    "config",
]
